theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/icon-white.svg'
  home:
    head:
      title: site
  share_links:
    enabled: true
    email: true
    facebook: true
    linkedin: true
    mastodon: true
    telegram: true
    twitter: true
    whatsapp: true
